TOP = ../..
include $(TOP)/configure/CONFIG
#ARCH = win32-x86
#ARCH = win32-x86-debug
ARCH = windows-x64-static
#ARCH = windows-x64-debug
#ARCH = linux-x86
TARGETS = envPaths dllPath.bat
include $(TOP)/configure/RULES.ioc
